apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-enrollment-api.fullname" . }}
  labels:
    {{- include "customer-enrollment-api.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.apiKeySecret.value | b64enc | quote }}
